# add stages here 
# stages:
#   stage_name:
#     cmd: python src/stage_01______.py
#     deps:
#     - src/stage_01______.py
#     outs:
#     - output_data_of_file_path


stages:
  load_data:
    cmd: python src/stage_01_load_save.py --config=configs/config.yaml
    deps: 
      - src/stage_01_load_save.py
      - src/utils/common.py
      - configs/config.yaml
    outs:
      - data

  prepare_base_model:
    cmd: python src/stage_02_prepare_model.py --config=configs/config.yaml --params=params.yaml
    deps: 
      - src/stage_02_prepare_model.py
      - src/utils/common.py
      - src/utils/model.py
      - configs/config.yaml
    params:
      - IMAGE_SIZE
      - LEARNING_RATE
    outs:
      - artifacts/base_model/updated_base_model.h5
      - artifacts/base_model/base_model.h5

  prepare_callbacks:
    cmd: python src/stage_03_prepare_callbacks.py --config=configs/config.yaml --params=params.yaml
    deps: 
      - src/stage_03_prepare_callbacks.py
      - src/utils/common.py
      - src/utils/callbacks.py
      - configs/config.yaml
      - params.yaml
    outs:
      - artifacts/callbacks/checkpoint_cb.cb
      - artifacts/callbacks/tensorboard_cb.cb

  train:
    cmd: python src/stage_04_train.py --config=configs/config.yaml --params=params.yaml
    deps: 
      - src/stage_04_train_model.py
      - src/utils/common.py
      - src/utils/model.py
      - src/utils/callbacks.py
      - src/utils/data_management.py
      - configs/config.yaml
      - data
      - artifacts/base_model/updated_base_model.h5
      - artifacts/callbacks/checkpoint_cb.cb
      - artifacts/callbacks/tensorboard_cb.cb
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
      - EPOCHS
      - AUGMENTATION
    outs:
      - artifacts/model