# This contains params to be used by the stages to train or predict

IMAGE_SIZE: [28, 28, 1]
CLASSES: 10
BATCH_SIZE: 64
EPOCHS: 5
DROPOUT_RATE: 0.5
LEARNING_RATE: 0.009
KERNEL_SIZE: 3
NUM_FILTERS: 128
NUM_NEURONS: 256
